// Generated by https://quicktype.io

class Peliculas {
  List<Pelicula> items = [];
  Peliculas();

  Peliculas.fromJsonList(List<dynamic> jsonList) {
    if (jsonList.isEmpty) return;
    for (var item in jsonList) {
      final pelicula = new Pelicula.fromJsonMap(item);
      items.add(pelicula);
    }
  }
}

class Pelicula {
  late bool adult;
  late String backdropPath;
  late List<int> genreIds;
  late int id;
  late OriginalLanguage originalLanguage;
  late String originalTitle;
  late String overview;
  late double popularity;
  late String posterPath;
  late String releaseDate;
  late String title;
  late bool video;
  late double voteAverage;
  late int voteCount;

  Pelicula({
    required this.adult,
    required this.backdropPath,
    required this.genreIds,
    required this.id,
    required this.originalLanguage,
    required this.originalTitle,
    required this.overview,
    required this.popularity,
    required this.posterPath,
    required this.releaseDate,
    required this.title,
    required this.video,
    required this.voteAverage,
    required this.voteCount,
  });

  Pelicula.fromJsonMap(Map<String, dynamic> json) {
    adult = json['adult'];
    backdropPath = json['backdrop_path'] ?? '';
    genreIds = json['genre_ids'].cast<int>();
    id = json['id'];
    String originalLanguageValue = json['original_language'];
    if (originalLanguageValue == 'en') {
      originalLanguage = OriginalLanguage.EN;
    } else if (originalLanguageValue == 'es') {
      originalLanguage = OriginalLanguage.ES;
    } else {
      originalLanguage = OriginalLanguage.FI;
    }
    originalTitle = json['original_title'];
    overview = json['overview'];
    popularity = json['popularity'] / 1;
    posterPath = json['poster_path'];
    releaseDate = json['release_date'];
    title = json['title'];
    video = json['video'];
    voteAverage = json['vote_average'] / 1;
    voteCount = json['vote_count'];
  }

  getPosterImg() {
    if (posterPath == null) {
      return 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.123rf.com%2Fphoto_104672510_stock-vector-no-image-available-icon-flat-vector-no-photo-sign-isolated-on-white-no-image-symbol-.html&psig=AOvVaw0Q4Z3Z2Z2Z2Z2Z2Z2Z2Z2Z2Z2Z2Z2Z2Z2Z2&ust=1634175449124000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjQ4ZqH0_MCFQAAAAAdAAAAABAD';
    } else {
      return 'https://image.tmdb.org/t/p/w500/$posterPath';
    }
  }
}

enum OriginalLanguage { EN, ES, FI }
